spring.application.name=Courier

spring.datasource.url=jdbc:mysql://localhost:3306/courierdb
spring.datasource.username=root
spring.datasource.password=Ramesh@7019

spring.jpa.hibernate.ddl-auto=update